#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=50G
#SBATCH --gpus=A40:1
#SBATCH --time=2-00:00:00
#SBATCH --output=logs/%x_job_%j.out
#SBATCH --job-name=oareactdiff_train
#SBATCH --partition=slowlane

source ~/.bashrc
conda activate reactot

time_date=$(date +%Y_%m_%d_%H_%M_%S)
echo "Job started on: ${time_date}"

echo "Starting training"

python -u train_ts1x.py
# python -u train_ts1x_self_supervised.py